version: "3.8"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
    depends_on:
      - nodejs
